/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/client" />

interface ImportMetaEnv {
  readonly VITE_SUPABASE_ANON_KEY?: string;
  readonly VITE_SUPABASE_LIST_INTERACTIONS_SCHEMA?: string;
  readonly VITE_SUPABASE_LIST_INTERACTIONS_TABLE?: string;
  readonly VITE_SUPABASE_LIST_INTERACTIONS_USER_COLUMN?: string;
  readonly VITE_SUPABASE_MOVIE_LIBRARY_SCHEMA?: string;
  readonly VITE_SUPABASE_MOVIE_LIBRARY_TABLE?: string;
  readonly VITE_SUPABASE_MOVIE_LIBRARY_USER_COLUMN?: string;
  readonly VITE_SUPABASE_RATING_HISTORY_SCHEMA?: string;
  readonly VITE_SUPABASE_RATING_HISTORY_TABLE?: string;
  readonly VITE_SUPABASE_RATING_HISTORY_USER_COLUMN?: string;
  readonly VITE_SUPABASE_RATINGS_SCHEMA?: string;
  readonly VITE_SUPABASE_RATINGS_TABLE?: string;
  readonly VITE_SUPABASE_RATINGS_USER_COLUMN?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_CONTEXT_SCHEMA?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_CONTEXT_TABLE?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_CONTEXT_USER_COLUMN?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_CONTEXT_WEIGHTS_SCHEMA?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_CONTEXT_WEIGHTS_TABLE?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_EXCLUSIONS_SCHEMA?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_EXCLUSIONS_TABLE?: string;
  readonly VITE_SUPABASE_RECOMMENDATION_EXCLUSIONS_USER_COLUMN?: string;
  readonly VITE_SUPABASE_URL?: string;
  readonly VITE_SUPABASE_USER_LISTS_SCHEMA?: string;
  readonly VITE_SUPABASE_USER_LISTS_TABLE?: string;
  readonly VITE_SUPABASE_USER_LISTS_USER_COLUMN?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
