create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  movie_id text not null,
  status text not null check (status in ('not_seen', 'dislike', 'like')),
  rating numeric(2, 1) null check (rating is null or rating between 0.5 and 5.0),
  review_tags text[] not null default '{}',
  favorite_character text null,
  answered_at timestamptz not null default timezone('utc', now()),
  raw_decision text null check (raw_decision is null or raw_decision in ('not_seen', 'dislike', 'like', 'not_interested')),
  detail_completed boolean not null default false,
  review_text text not null default '',
  question_text text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint ratings_user_movie_unique unique (user_id, movie_id)
);

create index if not exists ratings_user_id_idx on public.ratings (user_id);
create index if not exists ratings_answered_at_idx on public.ratings (answered_at desc);

drop trigger if exists set_ratings_updated_at on public.ratings;
create trigger set_ratings_updated_at
before update on public.ratings
for each row
execute function public.set_updated_at();

alter table public.ratings enable row level security;

drop policy if exists "Users can read own ratings" on public.ratings;
create policy "Users can read own ratings"
on public.ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own ratings" on public.ratings;
create policy "Users can insert own ratings"
on public.ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own ratings" on public.ratings;
create policy "Users can update own ratings"
on public.ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own ratings" on public.ratings;
create policy "Users can delete own ratings"
on public.ratings
for delete
to authenticated
using (auth.uid() = user_id);
