create extension if not exists pgcrypto;

create table if not exists public.rating_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  movie_id text not null,
  status text not null check (status in ('not_seen', 'dislike', 'like')),
  rating numeric(2, 1) null check (rating is null or rating between 0.5 and 5.0),
  review_tags text[] not null default '{}',
  favorite_character text null,
  answered_at timestamptz not null default timezone('utc', now()),
  raw_decision text null check (raw_decision is null or raw_decision in ('not_seen', 'dislike', 'like', 'not_interested')),
  detail_completed boolean not null default false,
  review_text text not null default '',
  question_text text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rating_history_user_movie_unique unique (user_id, movie_id)
);

create index if not exists rating_history_user_id_idx on public.rating_history (user_id);
create index if not exists rating_history_answered_at_idx on public.rating_history (answered_at desc);

drop trigger if exists set_rating_history_updated_at on public.rating_history;
create trigger set_rating_history_updated_at
before update on public.rating_history
for each row
execute function public.set_updated_at();

alter table public.rating_history enable row level security;

drop policy if exists "Users can read own rating history" on public.rating_history;
create policy "Users can read own rating history"
on public.rating_history
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own rating history" on public.rating_history;
create policy "Users can insert own rating history"
on public.rating_history
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own rating history" on public.rating_history;
create policy "Users can update own rating history"
on public.rating_history
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own rating history" on public.rating_history;
create policy "Users can delete own rating history"
on public.rating_history
for delete
to authenticated
using (auth.uid() = user_id);
