create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.user_lists (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  owner_name text not null default '나',
  title text not null,
  movie_ids text[] not null default '{}',
  save_count integer not null default 0 check (save_count >= 0),
  average_rating numeric(2, 1) not null default 0 check (average_rating between 0 and 5),
  rating_count integer not null default 0 check (rating_count >= 0),
  is_private boolean not null default false,
  source_list_id text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists user_lists_user_source_list_unique_idx
on public.user_lists (user_id, source_list_id)
where source_list_id is not null;

create index if not exists user_lists_user_id_idx on public.user_lists (user_id);
create index if not exists user_lists_updated_at_idx on public.user_lists (updated_at desc);

drop trigger if exists set_user_lists_updated_at on public.user_lists;
create trigger set_user_lists_updated_at
before update on public.user_lists
for each row
execute function public.set_updated_at();

alter table public.user_lists enable row level security;

drop policy if exists "Users can read own user lists" on public.user_lists;
create policy "Users can read own user lists"
on public.user_lists
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own user lists" on public.user_lists;
create policy "Users can insert own user lists"
on public.user_lists
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own user lists" on public.user_lists;
create policy "Users can update own user lists"
on public.user_lists
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own user lists" on public.user_lists;
create policy "Users can delete own user lists"
on public.user_lists
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.list_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  list_id text not null,
  saved boolean not null default false,
  personal_rating numeric(2, 1) null check (personal_rating is null or personal_rating between 0.5 and 5.0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint list_interactions_user_list_unique unique (user_id, list_id)
);

create index if not exists list_interactions_user_id_idx on public.list_interactions (user_id);
create index if not exists list_interactions_list_id_idx on public.list_interactions (list_id);

drop trigger if exists set_list_interactions_updated_at on public.list_interactions;
create trigger set_list_interactions_updated_at
before update on public.list_interactions
for each row
execute function public.set_updated_at();

alter table public.list_interactions enable row level security;

drop policy if exists "Users can read own list interactions" on public.list_interactions;
create policy "Users can read own list interactions"
on public.list_interactions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own list interactions" on public.list_interactions;
create policy "Users can insert own list interactions"
on public.list_interactions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own list interactions" on public.list_interactions;
create policy "Users can update own list interactions"
on public.list_interactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own list interactions" on public.list_interactions;
create policy "Users can delete own list interactions"
on public.list_interactions
for delete
to authenticated
using (auth.uid() = user_id);
