// TMDB keyword curation for the catalog snapshot. Keep this list in sync with
// the `true_story` context tag generated by the TMDB sync script.
export const trueStoryTmdbMovieIds = new Set<number>([
  359724, // Ford v Ferrari
  11423, // Memories of Murder
  872585, // Oppenheimer
  37799, // The Social Network
  597, // Titanic
  77338, // The Intouchables
  15804, // A Brighter Summer Day
  106646, // The Wolf of Wall Street
  374720, // Dunkirk
  490132, // Green Book
  855, // Black Hawk Down
  5879, // In the Realm of the Senses
  799583, // The Ministry of Ungentlemanly Warfare
  581528, // The Gangster, the Cop, the Devil
  197, // Braveheart
  453, // A Beautiful Mind
  753342, // Napoleon
  190859, // American Sniper
  15121 // The Sound of Music
]);
